# Generated by Django 3.0.3 on 2020-02-27 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='init_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In progress', 'Inprogress'), ('Waiting', 'Waiting'), ('Closed', 'Closed')], default='New', max_length=60),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='init_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('RS', 'Estudiante por requerimientos'), ('PS', 'Estudiante fijo'), ('TR', 'Trainee'), ('JR', 'Junior'), ('SS', 'Semi-Senior'), ('SR', 'Senior')], default='RS', max_length=60),
        ),
    ]
