# Generated by Django 3.0.3 on 2020-02-27 22:54

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200227_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('RS', 'Estudiante por requerimientos'), ('PS', 'Estudiante fijo'), ('TR', 'Trainee'), ('JR', 'Junior'), ('SS', 'Semi-Senior'), ('SR', 'Senior')], default=accounts.utils.UserPosition['RS'], max_length=60),
        ),
    ]
