# Generated by Django 3.0.3 on 2020-02-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200227_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('RS', 'Estudiante por requerimientos'), ('PS', 'Estudiante fijo'), ('TR', 'Trainee'), ('JR', 'Junior'), ('SS', 'Semi-Senior'), ('SR', 'Senior')], default='RS', max_length=60),
        ),
    ]
