# Generated by Django 3.0.3 on 2020-03-09 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200227_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='init_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
