# Generated by Django 3.0.3 on 2020-03-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200312_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTaskAssignRelation',
        ),
    ]
