# Generated by Django 3.0.3 on 2020-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_advancement_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='advancement',
            name='init_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='aproved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='init_date',
        ),
        migrations.AddField(
            model_name='advancement',
            name='quantity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
